# Generated by Django 5.0.1 on 2024-01-26 16:38

import ckeditor.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('story_title', models.CharField(max_length=200)),
                ('place_name', models.CharField(max_length=200)),
                ('city_name', models.CharField(max_length=250)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='thumbnails/')),
                ('photos', models.ImageField(blank=True, null=True, upload_to='photos/')),
                ('nearby_places', models.CharField(max_length=200)),
                ('food_to_try', models.CharField(max_length=200)),
                ('precautions', models.CharField(max_length=200)),
                ('things_to_try', models.CharField(max_length=200)),
                ('visit_season', models.CharField(max_length=200)),
                ('trip_highlights', models.TextField()),
                ('brief_summary', ckeditor.fields.RichTextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
